import {
  Baby,
  BarChart,
  BookOpenText,
  Briefcase,
  Camera,
  Clapperboard,
  Cpu,
  Dumbbell,
  Gamepad2,
  Heart,
  HeartPulse,
  Music,
  Package,
  Palette,
  PartyPopper,
  PawPrint,
  Rocket,
  Scissors,
  ShoppingBag,
  Tent,
  Theater,
  UtensilsCrossed,
} from "lucide-react";

export const CATEGORIES = [
  { id: 1, icon: Tent, label: "戶外體驗" },
  { id: 2, icon: BookOpenText, label: "學習" },
  { id: 3, icon: Baby, label: "親子" },
  { id: 4, icon: PawPrint, label: "寵物" },
  { id: 5, icon: Cpu, label: "科技" },
  { id: 6, icon: Briefcase, label: "商業" },
  { id: 7, icon: Rocket, label: "創業" },
  { id: 8, icon: BarChart, label: "投資" },
  { id: 9, icon: Palette, label: "設計" },
  { id: 10, icon: Theater, label: "藝文" },
  { id: 11, icon: Scissors, label: "手作" },
  { id: 12, icon: UtensilsCrossed, label: "美食" },
  { id: 13, icon: Camera, label: "攝影" },
  { id: 14, icon: Gamepad2, label: "遊戲" },
  { id: 15, icon: Dumbbell, label: "運動" },
  { id: 16, icon: HeartPulse, label: "健康" },
  { id: 17, icon: Music, label: "音樂" },
  { id: 18, icon: Clapperboard, label: "電影" },
  { id: 19, icon: PartyPopper, label: "娛樂" },
  { id: 20, icon: Package, label: "區塊鏈" },
  { id: 21, icon: ShoppingBag, label: "時尚" },
  { id: 22, icon: Heart, label: "公益" },
];
