// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type Options as ClientOptions,
  type TDataShape,
  formDataBodySerializer,
} from "@hey-api/client-next";
import { client as _heyApiClient } from "./client.gen";
import type {
  DeleteApiV1ActivitiesByActivityIdTicketTypesByTicketTypeIdData,
  DeleteApiV1ActivitiesByActivityIdTicketTypesByTicketTypeIdError,
  DeleteApiV1ActivitiesByActivityIdTicketTypesByTicketTypeIdResponse,
  DeleteApiV1OrganizationsData,
  DeleteApiV1OrganizationsError,
  DeleteApiV1OrganizationsResponse,
  GetApiV1ActivitiesByActivityIdData,
  GetApiV1ActivitiesByActivityIdError,
  GetApiV1ActivitiesByActivityIdResponse,
  GetApiV1ActivitiesByActivityIdTicketTypesData,
  GetApiV1ActivitiesByActivityIdTicketTypesError,
  GetApiV1ActivitiesByActivityIdTicketTypesResponse,
  GetApiV1ActivitiesData,
  GetApiV1ActivitiesError,
  GetApiV1ActivitiesResponse,
  GetApiV1CurrenciesData,
  GetApiV1CurrenciesResponse,
  GetApiV1OrganizationsByOrganizationIdData,
  GetApiV1OrganizationsByOrganizationIdError,
  GetApiV1OrganizationsByOrganizationIdResponse,
  GetApiV1OrganizationsData,
  GetApiV1OrganizationsError,
  GetApiV1OrganizationsResponse,
  GetApiV1UsersGoogleCallbackData,
  GetApiV1UsersGoogleLoginData,
  GetApiV1UsersProfileData,
  GetApiV1UsersProfileError,
  GetApiV1UsersProfileResponse,
  PatchApiV1ActivitiesByActivityIdBasicData,
  PatchApiV1ActivitiesByActivityIdBasicError,
  PatchApiV1ActivitiesByActivityIdBasicResponse,
  PatchApiV1ActivitiesByActivityIdCancelData,
  PatchApiV1ActivitiesByActivityIdCancelError,
  PatchApiV1ActivitiesByActivityIdCancelResponse,
  PatchApiV1ActivitiesByActivityIdCategoriesData,
  PatchApiV1ActivitiesByActivityIdCategoriesError,
  PatchApiV1ActivitiesByActivityIdCategoriesResponse,
  PatchApiV1ActivitiesByActivityIdContentData,
  PatchApiV1ActivitiesByActivityIdContentError,
  PatchApiV1ActivitiesByActivityIdContentResponse,
  PatchApiV1ActivitiesByActivityIdPublishData,
  PatchApiV1ActivitiesByActivityIdPublishError,
  PatchApiV1ActivitiesByActivityIdPublishResponse,
  PostApiV1ActivitiesByActivityIdTicketTypesData,
  PostApiV1ActivitiesByActivityIdTicketTypesError,
  PostApiV1ActivitiesByActivityIdTicketTypesResponse,
  PostApiV1ActivitiesData,
  PostApiV1ActivitiesError,
  PostApiV1ActivitiesResponse,
  PostApiV1CurrenciesData,
  PostApiV1CurrenciesError,
  PostApiV1CurrenciesResponse,
  PostApiV1OrganizationsData,
  PostApiV1OrganizationsError,
  PostApiV1OrganizationsResponse,
  PostApiV1UsersLoginData,
  PostApiV1UsersLoginError,
  PostApiV1UsersLoginResponse,
  PostApiV1UsersProfileAvatarData,
  PostApiV1UsersProfileAvatarError,
  PostApiV1UsersProfileAvatarResponse,
  PostApiV1UsersSignupData,
  PostApiV1UsersSignupError,
  PostApiV1UsersSignupResponse,
  PutApiV1ActivitiesByActivityIdData,
  PutApiV1ActivitiesByActivityIdError,
  PutApiV1ActivitiesByActivityIdResponse,
  PutApiV1ActivitiesByActivityIdTicketTypesByTicketTypeIdData,
  PutApiV1ActivitiesByActivityIdTicketTypesByTicketTypeIdError,
  PutApiV1ActivitiesByActivityIdTicketTypesByTicketTypeIdResponse,
  PutApiV1OrganizationsData,
  PutApiV1OrganizationsError,
  PutApiV1OrganizationsResponse,
  PutApiV1UsersForgetData,
  PutApiV1UsersForgetError,
  PutApiV1UsersForgetResponse,
  PutApiV1UsersProfileData,
  PutApiV1UsersProfileError,
  PutApiV1UsersProfileResponse,
  PutApiV1UsersResetPasswordData,
  PutApiV1UsersResetPasswordError,
  PutApiV1UsersResetPasswordResponse,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * 獲取活動資料
 * 獲取活動資料
 */
export const getApiV1Activities = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1ActivitiesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetApiV1ActivitiesResponse,
    GetApiV1ActivitiesError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/activities",
    ...options,
  });
};

/**
 * 新增一筆活動資料
 * 在選擇活動形式為線上或線下後，即新增一筆活動資料到db中
 */
export const postApiV1Activities = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1ActivitiesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiV1ActivitiesResponse,
    PostApiV1ActivitiesError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/activities",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * 取得某一活動的所有票種資訊
 * 當使用者要報名一個活動時，會先取得這一個活動的所有票種資訊，例如：一般票、早鳥票等等
 */
export const getApiV1ActivitiesByActivityIdTicketTypes = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1ActivitiesByActivityIdTicketTypesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiV1ActivitiesByActivityIdTicketTypesResponse,
    GetApiV1ActivitiesByActivityIdTicketTypesError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/activities/{activityId}/ticketTypes",
    ...options,
  });
};

/**
 * 新增特定活動票種
 * 主辦方在創建活動時所用之新增票種功能
 */
export const postApiV1ActivitiesByActivityIdTicketTypes = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1ActivitiesByActivityIdTicketTypesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiV1ActivitiesByActivityIdTicketTypesResponse,
    PostApiV1ActivitiesByActivityIdTicketTypesError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/activities/{activityId}/ticketTypes",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * 刪除特定活動之單一票種
 * 主辦方刪除票種功能
 */
export const deleteApiV1ActivitiesByActivityIdTicketTypesByTicketTypeId = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteApiV1ActivitiesByActivityIdTicketTypesByTicketTypeIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteApiV1ActivitiesByActivityIdTicketTypesByTicketTypeIdResponse,
    DeleteApiV1ActivitiesByActivityIdTicketTypesByTicketTypeIdError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/activities/{activityId}/ticketTypes/{ticketTypeId}",
    ...options,
  });
};

/**
 * 編輯特定活動之單一票種
 * 主辦方編輯票種功能
 */
export const putApiV1ActivitiesByActivityIdTicketTypesByTicketTypeId = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutApiV1ActivitiesByActivityIdTicketTypesByTicketTypeIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<
    PutApiV1ActivitiesByActivityIdTicketTypesByTicketTypeIdResponse,
    PutApiV1ActivitiesByActivityIdTicketTypesByTicketTypeIdError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/activities/{activityId}/ticketTypes/{ticketTypeId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * 獲取特定的活動資料
 * 獲取特定活動資料
 */
export const getApiV1ActivitiesByActivityId = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1ActivitiesByActivityIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiV1ActivitiesByActivityIdResponse,
    GetApiV1ActivitiesByActivityIdError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/activities/{activityId}",
    ...options,
  });
};

/**
 * 更新活動資料
 * 更新活動資料
 */
export const putApiV1ActivitiesByActivityId = <ThrowOnError extends boolean = false>(
  options: Options<PutApiV1ActivitiesByActivityIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<
    PutApiV1ActivitiesByActivityIdResponse,
    PutApiV1ActivitiesByActivityIdError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/activities/{activityId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * 新增活動時，設定活動主題步驟
 * 設定活動主題，至少要選擇一個主題，最多兩個，帶入主題ID array
 */
export const patchApiV1ActivitiesByActivityIdCategories = <ThrowOnError extends boolean = false>(
  options: Options<PatchApiV1ActivitiesByActivityIdCategoriesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchApiV1ActivitiesByActivityIdCategoriesResponse,
    PatchApiV1ActivitiesByActivityIdCategoriesError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/activities/{activityId}/categories",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * 新增活動時，設定基本資料步驟
 * 新增活動時的基本資料步驟，包含活動名稱、活動起迄時間、活動地點
 */
export const patchApiV1ActivitiesByActivityIdBasic = <ThrowOnError extends boolean = false>(
  options: Options<PatchApiV1ActivitiesByActivityIdBasicData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchApiV1ActivitiesByActivityIdBasicResponse,
    PatchApiV1ActivitiesByActivityIdBasicError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/activities/{activityId}/basic",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * 新增活動時，設定詳細內容步驟
 * 新增活動時的詳細內容步驟，包含活動簡介、活動詳細內容
 */
export const patchApiV1ActivitiesByActivityIdContent = <ThrowOnError extends boolean = false>(
  options: Options<PatchApiV1ActivitiesByActivityIdContentData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchApiV1ActivitiesByActivityIdContentResponse,
    PatchApiV1ActivitiesByActivityIdContentError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/activities/{activityId}/content",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * 新增活動時最後一步驟，發布活動
 * 前置步驟都設定完成後的最後一步，發布活動，所有使用者皆可看到此活動
 */
export const patchApiV1ActivitiesByActivityIdPublish = <ThrowOnError extends boolean = false>(
  options: Options<PatchApiV1ActivitiesByActivityIdPublishData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchApiV1ActivitiesByActivityIdPublishResponse,
    PatchApiV1ActivitiesByActivityIdPublishError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/activities/{activityId}/publish",
    ...options,
  });
};

/**
 * 取消活動
 * 將活動狀態改為canceled
 */
export const patchApiV1ActivitiesByActivityIdCancel = <ThrowOnError extends boolean = false>(
  options: Options<PatchApiV1ActivitiesByActivityIdCancelData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchApiV1ActivitiesByActivityIdCancelResponse,
    PatchApiV1ActivitiesByActivityIdCancelError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/activities/{activityId}/cancel",
    ...options,
  });
};

/**
 * Get all currencies
 */
export const getApiV1Currencies = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1CurrenciesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<GetApiV1CurrenciesResponse, unknown, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/currencies",
    ...options,
  });
};

/**
 * Create a new currency
 */
export const postApiV1Currencies = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1CurrenciesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiV1CurrenciesResponse,
    PostApiV1CurrenciesError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/currencies",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * 刪除主辦單位
 * 刪除主辦單位
 */
export const deleteApiV1Organizations = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiV1OrganizationsData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteApiV1OrganizationsResponse,
    DeleteApiV1OrganizationsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/organizations",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * 取得主辦單位列表
 * 取得當前使用者的主辦單位列表
 */
export const getApiV1Organizations = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1OrganizationsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetApiV1OrganizationsResponse,
    GetApiV1OrganizationsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/organizations",
    ...options,
  });
};

/**
 * 創建主辦單位
 * 創建新的主辦單位
 */
export const postApiV1Organizations = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1OrganizationsData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiV1OrganizationsResponse,
    PostApiV1OrganizationsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/organizations",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * 更新主辦單位
 * 更新主辦單位資料
 */
export const putApiV1Organizations = <ThrowOnError extends boolean = false>(
  options: Options<PutApiV1OrganizationsData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<
    PutApiV1OrganizationsResponse,
    PutApiV1OrganizationsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/organizations",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * 取得主辦單位詳細資料
 * 取得主辦單位詳細資料
 */
export const getApiV1OrganizationsByOrganizationId = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1OrganizationsByOrganizationIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiV1OrganizationsByOrganizationIdResponse,
    GetApiV1OrganizationsByOrganizationIdError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/organizations/{organizationId}",
    ...options,
  });
};

/**
 * 用戶註冊
 * 創建新用戶帳號
 */
export const postApiV1UsersSignup = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1UsersSignupData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiV1UsersSignupResponse,
    PostApiV1UsersSignupError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/signup",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * 用戶登入
 * 用戶登入系統並獲取 JWT 認證 Token
 */
export const postApiV1UsersLogin = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1UsersLoginData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiV1UsersLoginResponse,
    PostApiV1UsersLoginError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Google OAuth 登入
 * 開始 Google OAuth 認證流程，重定向至 Google 登入頁面
 */
export const getApiV1UsersGoogleLogin = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1UsersGoogleLoginData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/google/login",
    ...options,
  });
};

/**
 * Google OAuth 回調
 * Google 認證完成後的回調處理
 */
export const getApiV1UsersGoogleCallback = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1UsersGoogleCallbackData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/google/callback",
    ...options,
  });
};

/**
 * 請求密碼重設
 * 發送重設密碼郵件至指定信箱
 */
export const putApiV1UsersForget = <ThrowOnError extends boolean = false>(
  options: Options<PutApiV1UsersForgetData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<
    PutApiV1UsersForgetResponse,
    PutApiV1UsersForgetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/forget",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * 確認密碼重設
 * 使用重設令牌和新密碼完成密碼重設
 */
export const putApiV1UsersResetPassword = <ThrowOnError extends boolean = false>(
  options: Options<PutApiV1UsersResetPasswordData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<
    PutApiV1UsersResetPasswordResponse,
    PutApiV1UsersResetPasswordError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/resetPassword",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * 獲取用戶資料
 * 獲取當前登入用戶的資料
 */
export const getApiV1UsersProfile = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1UsersProfileData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetApiV1UsersProfileResponse,
    GetApiV1UsersProfileError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/profile",
    ...options,
  });
};

/**
 * 更新用戶資料
 * 更新當前登入用戶的資料
 */
export const putApiV1UsersProfile = <ThrowOnError extends boolean = false>(
  options?: Options<PutApiV1UsersProfileData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).put<
    PutApiV1UsersProfileResponse,
    PutApiV1UsersProfileError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/profile",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * 上傳用戶頭像
 * 上傳一張圖片作為當前登入用戶的大頭貼，圖片將會上傳至 Imgur 並儲存其 URL 至 DB
 */
export const postApiV1UsersProfileAvatar = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1UsersProfileAvatarData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiV1UsersProfileAvatarResponse,
    PostApiV1UsersProfileAvatarError,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/profile/avatar",
    ...options,
    headers: {
      "Content-Type": null,
      ...options?.headers,
    },
  });
};