// This file is auto-generated by @hey-api/openapi-ts

export type ErrorResponse = {
  message?: string;
  status?: boolean;
};

export type CurrencyResponse = {
  id?: string;
  code?: string;
  name?: string;
};

export type CreateCurrencyRequest = {
  code: string;
  name: string;
};

export type UserResponse = {
  id?: string;
  memberId?: string;
  email?: string;
  name?: string | null;
  avatar?: string | null;
  displayName?: string | null;
  birthday?: string | null;
  gender?: string | null;
  phoneNumber?: string | null;
  countryCode?: string | null;
  region?: string | null;
  address?: string | null;
  identity?: string | null;
  createdAt?: string;
};

export type LoginRequest = {
  /**
   * 使用者電子郵件地址
   */
  email: string;
  /**
   * 使用者密碼
   */
  password: string;
};

export type LoginResponse = {
  message?: string;
  status?: boolean;
  /**
   * JWT Token
   */
  data?: string;
};

export type SignupRequest = {
  /**
   * 用戶電子郵件，將作為登入帳號
   */
  email: string;
  /**
   * 用戶密碼
   */
  password: string;
  /**
   * 確認密碼，必須與密碼一致
   */
  checkPassword: string;
};

export type SignupResponse = {
  message?: string;
  status?: boolean;
};

export type UpdateProfileRequest = {
  /**
   * 用戶真實姓名
   */
  name?: string;
  /**
   * 用戶電子郵件
   */
  email?: string;
  /**
   * 用戶頭像 URL
   */
  avatar?: string;
  /**
   * 用戶顯示名稱
   */
  displayName?: string;
  /**
   * 用戶生日 (格式: YYYY/MM/DD)
   */
  birthday?: string;
  /**
   * 性別
   */
  gender?: string;
  /**
   * 電話號碼
   */
  phoneNumber?: string;
  /**
   * 國家代碼
   */
  countryCode?: string;
  /**
   * 地區
   */
  region?: string;
  /**
   * 地址
   */
  address?: string;
  /**
   * 身分識別
   */
  identity?: string;
};

export type UpdateProfileResponse = {
  message?: string;
  status?: boolean;
};

export type GetApiV1CurrenciesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/currencies";
};

export type GetApiV1CurrenciesResponses = {
  /**
   * A list of currencies
   */
  200: Array<CurrencyResponse>;
};

export type GetApiV1CurrenciesResponse =
  GetApiV1CurrenciesResponses[keyof GetApiV1CurrenciesResponses];

export type PostApiV1CurrenciesData = {
  body: CreateCurrencyRequest;
  path?: never;
  query?: never;
  url: "/api/v1/currencies";
};

export type PostApiV1CurrenciesErrors = {
  /**
   * Bad request
   */
  400: ErrorResponse;
};

export type PostApiV1CurrenciesError = PostApiV1CurrenciesErrors[keyof PostApiV1CurrenciesErrors];

export type PostApiV1CurrenciesResponses = {
  /**
   * The created currency
   */
  201: CurrencyResponse;
};

export type PostApiV1CurrenciesResponse =
  PostApiV1CurrenciesResponses[keyof PostApiV1CurrenciesResponses];

export type PostApiV1UsersSignupData = {
  body: SignupRequest;
  path?: never;
  query?: never;
  url: "/api/v1/users/signup";
};

export type PostApiV1UsersSignupErrors = {
  /**
   * 請求錯誤
   */
  400: ErrorResponse;
};

export type PostApiV1UsersSignupError =
  PostApiV1UsersSignupErrors[keyof PostApiV1UsersSignupErrors];

export type PostApiV1UsersSignupResponses = {
  /**
   * 註冊成功
   */
  201: SignupResponse;
};

export type PostApiV1UsersSignupResponse =
  PostApiV1UsersSignupResponses[keyof PostApiV1UsersSignupResponses];

export type PostApiV1UsersLoginData = {
  body: LoginRequest;
  path?: never;
  query?: never;
  url: "/api/v1/users/login";
};

export type PostApiV1UsersLoginErrors = {
  /**
   * 請求錯誤
   */
  400: ErrorResponse;
};

export type PostApiV1UsersLoginError = PostApiV1UsersLoginErrors[keyof PostApiV1UsersLoginErrors];

export type PostApiV1UsersLoginResponses = {
  /**
   * 登入成功
   */
  200: LoginResponse;
};

export type PostApiV1UsersLoginResponse =
  PostApiV1UsersLoginResponses[keyof PostApiV1UsersLoginResponses];

export type GetApiV1UsersProfileData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/users/profile";
};

export type GetApiV1UsersProfileErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 用戶不存在
   */
  404: ErrorResponse;
};

export type GetApiV1UsersProfileError =
  GetApiV1UsersProfileErrors[keyof GetApiV1UsersProfileErrors];

export type GetApiV1UsersProfileResponses = {
  /**
   * 成功獲取用戶資料
   */
  200: {
    message?: string;
    status?: boolean;
    data?: UserResponse;
  };
};

export type GetApiV1UsersProfileResponse =
  GetApiV1UsersProfileResponses[keyof GetApiV1UsersProfileResponses];

export type PutApiV1UsersProfileData = {
  body?: UpdateProfileRequest;
  path?: never;
  query?: never;
  url: "/api/v1/users/profile";
};

export type PutApiV1UsersProfileErrors = {
  /**
   * 請求錯誤
   */
  400: ErrorResponse;
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 用戶不存在
   */
  404: ErrorResponse;
};

export type PutApiV1UsersProfileError =
  PutApiV1UsersProfileErrors[keyof PutApiV1UsersProfileErrors];

export type PutApiV1UsersProfileResponses = {
  /**
   * 更新成功
   */
  200: UpdateProfileResponse;
};

export type PutApiV1UsersProfileResponse =
  PutApiV1UsersProfileResponses[keyof PutApiV1UsersProfileResponses];

export type ClientOptions = {
  baseUrl: "https://eventa-backend-pgun.onrender.com" | (string & {});
};
