name: 構建與部署

on:
  push:
    branches: [develop]

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/eventa-frontend
  NEXT_PUBLIC_API_BASE_URL: ${{ vars.NEXT_PUBLIC_API_BASE_URL }}

jobs:
  build-and-deploy:
    name: 多架構建構與部署
    runs-on: ubuntu-latest

    steps:
      - name: 檢出程式碼
        uses: actions/checkout@v4

      - name: 安裝依賴並執行建構
        run: |
          npm ci
          npm run build

      - name: 將建構的檔案複製到上下文目錄
        run: |
          mkdir -p context/.next
          cp -r .next/standalone context/.next/
          cp -r .next/static context/.next/
          cp -r public context/
          cp package.json context/
          cp Dockerfile context/

      - name: 啟用 QEMU（支援跨架構建構）
        uses: docker/setup-qemu-action@v3

      - name: 設定 Buildx 建構器
        uses: docker/setup-buildx-action@v3

      - name: 登入 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 建構並推送多架構映像
        uses: docker/build-push-action@v5
        with:
          context: ./context
          file: ./context/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,ignore-error=true
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: 觸發 Render 自動部署
        run: curl -X GET "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
